/**
 * @file Defines routed feature page components for the contract tracker.
 */
import { BellRing, Clock3, ExternalLink, FileText, Inbox } from "lucide-react";
import { Link } from "react-router-dom";

import { InlineError } from "@/components/feedback/inline-error.js";
import { LoadingState } from "@/components/feedback/loading-state.js";
import { RetryPanel } from "@/components/feedback/retry-panel.js";
import { ContentContainer } from "@/components/layout/content-container.js";
import { PageHeader } from "@/components/layout/page-header.js";
import { Badge } from "@/components/ui/badge.js";
import { routePaths } from "@/app/route-paths.js";
import { formatDateTime } from "@/utils/format-date.js";
import { DataTable, TableHead } from "../../workflow/components.js";
import { useMessages } from "../hooks/use-messages.js";
import type { MessageSummary } from "../types/message.js";

/**
 * @description Performs the payload type helper operation for this module.
 * @param {unknown} payload - Input value for payload.
 * @returns {string} Result of the payload type operation.
 */
function payloadType(payload: unknown): string {
  if (typeof payload === "object" && payload !== null && "type" in payload) {
    const type = (payload as { readonly type?: unknown }).type;
    return typeof type === "string" ? type.replaceAll("_", " ") : "Reminder message";
  }
  return "Reminder message";
}

/**
 * @description Renders the message mobile card component for the contract tracker UI.
 * @param {{ readonly message: MessageSummary }} { message } - Input value for { message }.
 * @returns {JSX.Element} Result of the message mobile card operation.
 */
function MessageMobileCard({ message }: { readonly message: MessageSummary }) {
  const actionClassName =
    "inline-flex h-10 flex-1 items-center justify-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-700 shadow-card transition hover:bg-slate-50 focus-visible:shadow-focus active:translate-y-px";

  return (
    <article className="rounded-lg border border-slate-200 bg-white p-4 shadow-card">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="text-sm font-bold text-slate-950">{message.obligationTitle}</p>
          <p className="mt-1 truncate text-sm text-slate-500">{message.contractDisplayName}</p>
        </div>
        <Badge tone="info">{message.reminderStatus}</Badge>
      </div>
      <dl className="mt-4 grid grid-cols-2 gap-3 text-sm">
        <div>
          <dt className="text-xs font-semibold uppercase text-slate-500">Message</dt>
          <dd className="mt-1 capitalize text-slate-900">{payloadType(message.payload)}</dd>
        </div>
        <div>
          <dt className="text-xs font-semibold uppercase text-slate-500">Created</dt>
          <dd className="mt-1 text-slate-900">{formatDateTime(message.createdAt)}</dd>
        </div>
        <div className="col-span-2">
          <dt className="text-xs font-semibold uppercase text-slate-500">Scheduled</dt>
          <dd className="mt-1 text-slate-900">{formatDateTime(message.scheduledFor)}</dd>
        </div>
      </dl>
      <div className="sticky bottom-0 mt-4 flex gap-2 bg-white pt-3">
        <Link className={actionClassName} to={routePaths.obligationDetail(message.obligationId)}>
          <ExternalLink aria-hidden className="size-4" />
          Obligation
        </Link>
        <Link className={actionClassName} to={routePaths.contractDetail(message.contractId)}>
          <FileText aria-hidden className="size-4" />
          Contract
        </Link>
      </div>
    </article>
  );
}

/**
 * @description Renders the messages page component for the contract tracker UI.
 * @returns {JSX.Element} Result of the messages page operation.
 */
export function MessagesPage() {
  const actionClassName =
    "inline-flex h-9 items-center justify-center gap-1.5 rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-700 shadow-card transition hover:bg-slate-50 focus-visible:shadow-focus active:translate-y-px";
  const messages = useMessages({ limit: 50, offset: 0 });
  const rows = messages.data ?? [];
  const deliveredCount = rows.filter((message) => message.reminderStatus === "DELIVERED").length;
  const pendingCount = rows.length - deliveredCount;

  return (
    <ContentContainer>
      <PageHeader
        description="Review reminder messages generated by scheduled obligation notifications."
        title="Messages"
      />
      <div className="mb-5 grid gap-4 sm:grid-cols-3">
        <section className="rounded-lg border border-t-4 border-slate-200 border-t-teal-500 bg-white p-5 shadow-card">
          <div className="flex items-center justify-between">
            <p className="text-sm font-bold text-slate-600">Inbox Messages</p>
            <Inbox aria-hidden className="size-5 text-teal-700" />
          </div>
          <p className="mt-4 text-3xl font-bold text-slate-950">
            {messages.isSuccess ? rows.length : "Unavailable"}
          </p>
        </section>
        <section className="rounded-lg border border-t-4 border-emerald-200 border-t-emerald-500 bg-gradient-to-br from-white to-emerald-50 p-5 shadow-card">
          <div className="flex items-center justify-between">
            <p className="text-sm font-bold text-emerald-900">Delivered</p>
            <BellRing aria-hidden className="size-5 text-emerald-700" />
          </div>
          <p className="mt-4 text-3xl font-bold text-emerald-950">
            {messages.isSuccess ? deliveredCount : "Unavailable"}
          </p>
        </section>
        <section className="rounded-lg border border-t-4 border-amber-200 border-t-amber-500 bg-gradient-to-br from-white to-amber-50 p-5 shadow-card">
          <div className="flex items-center justify-between">
            <p className="text-sm font-bold text-amber-900">Needs Attention</p>
            <Clock3 aria-hidden className="size-5 text-amber-700" />
          </div>
          <p className="mt-4 text-3xl font-bold text-amber-950">
            {messages.isSuccess ? pendingCount : "Unavailable"}
          </p>
        </section>
      </div>
      {messages.isLoading ? <LoadingState /> : null}
      {messages.isError ? (
        <>
          <InlineError error={messages.error} />
          <RetryPanel error={messages.error} onRetry={() => void messages.refetch()} />
        </>
      ) : null}
      {messages.isSuccess && rows.length === 0 ? (
        <div className="rounded-lg border border-slate-200 bg-white p-6 text-sm text-slate-500 shadow-card">
          No reminder messages have been generated yet.
        </div>
      ) : null}
      {messages.isSuccess && rows.length > 0 ? (
        <>
          <div className="hidden md:block">
            <DataTable minWidth="min-w-[920px]">
              <TableHead
                columns={[
                  "Message",
                  "Obligation",
                  "Contract",
                  "Reminder Status",
                  "Scheduled",
                  "Created",
                  "Actions",
                ]}
              />
              <tbody className="divide-y divide-slate-200">
                {rows.map((message) => (
                  <tr className="transition-colors hover:bg-[#F0F9FF]" key={message.id}>
                    <td className="px-5 py-4 font-semibold capitalize text-slate-950">
                      {payloadType(message.payload)}
                    </td>
                    <td className="max-w-64 px-5 py-4">
                      <p className="truncate font-semibold text-slate-900">
                        {message.obligationTitle}
                      </p>
                    </td>
                    <td className="max-w-64 px-5 py-4">
                      <p className="truncate text-slate-700">{message.contractDisplayName}</p>
                    </td>
                    <td className="px-5 py-4">
                      <Badge tone={message.reminderStatus === "DELIVERED" ? "success" : "warning"}>
                        {message.reminderStatus}
                      </Badge>
                    </td>
                    <td className="px-5 py-4 text-slate-600">
                      {formatDateTime(message.scheduledFor)}
                    </td>
                    <td className="px-5 py-4 text-slate-600">
                      {formatDateTime(message.createdAt)}
                    </td>
                    <td className="px-5 py-4">
                      <div className="flex gap-2">
                        <Link
                          className={actionClassName}
                          to={routePaths.obligationDetail(message.obligationId)}
                        >
                          <ExternalLink aria-hidden className="size-4" />
                          Obligation
                        </Link>
                        <Link
                          className={actionClassName}
                          to={routePaths.contractDetail(message.contractId)}
                        >
                          <FileText aria-hidden className="size-4" />
                          Contract
                        </Link>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </DataTable>
          </div>
          <div className="space-y-3 md:hidden">
            {rows.map((message) => (
              <MessageMobileCard key={message.id} message={message} />
            ))}
          </div>
        </>
      ) : null}
    </ContentContainer>
  );
}
